name: oscam build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build oscam
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        gcc: [13]
    steps:
      - name: Install prerequisites
        run: |
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -q update
          sudo apt remove -y libunwind-14-dev
          sudo apt-get install g++-${{ matrix.gcc }}
          sudo apt-get install autoconf libccid automake libtool gettext make cmake tar bzip2 gzip patch ncurses-bin gcc g++ flex bison pkg-config pcsc-tools pkg-config wget libpcsclite1 libpcsclite-dev libusb-dev libssl-dev libpnglite-dev pngquant zlib1g-dev zlib1g dialog build-essential minizip
      - uses: actions/checkout@v3

      - name: Build oscam
        env:
          CC: "gcc-${{ matrix.gcc }}"
          CXX: "g++-${{ matrix.gcc }}"
        run: |
          echo "compiling oscam"
          mkdir build;cd build
          cmake -DWEBIF=1 -DHAVE=DVBAPI=1 ..
          make
          echo done!
